<a href="https://colab.research.google.com/github/Shishukumar74/Artificial_Neural_Network/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing** **Libraries**

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

# **Upload** **Dataset**

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [4]:
df = pd.read_csv('Churn_Modelling.csv')

In [5]:
df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
X = df.iloc[:, 3:-1].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
Y = df.iloc[:, -1].values
print(Y)

[1 0 1 ... 1 1 0]


# **Encoding** **Categorical** **Data**

In [9]:
# Label Encoding the "Gender" Column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
# One Hot Encoding the "Geography" Column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# **Splitting** **Dataset** **into Training and Test set**

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

# **Feature Scaling**

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Building Artificial Neural Network**

In [13]:
# Intializing the Artificial Neural Network
ann = tf.keras.models.Sequential()

In [14]:
# Add input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
# Add second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# Add output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# **Training Artificial Neural Network**

In [17]:
# Compiling the Artificial Neural Network
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# **Training Artificial Neural Network on the Training Set**

In [18]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5837 - accuracy: 0.7293
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4891 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4615 - accuracy: 0.7987
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4389 - accuracy: 0.8043
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4265 - accuracy: 0.8106
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8194
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4070 - accuracy: 0.8270
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3954 - accuracy: 0.8351
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3845 - accuracy: 0.8396
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3744 - accura

# **Predicting and Evaluating model**

In [28]:
# Geography: France
# Credit Score: 600
# Gender: Male
# Age: 40
# Tenure: 3 years
# Balance: $60000
# Number of Products: 2
# Have Credit Card: Yes
# Is active Member: Yes
# Estimated Salary: $50000
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 65000, 2, 1, 1, 50000]])))

[[0.02059019]]


# **Predicting Test set Result**

In [26]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred>0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# **Making Confusion Matrix**

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1533   62]
 [ 207  198]]


0.8655